/**
 * Expo Config Plugin: withOxyDebugSigning
 *
 * Signs debug builds with the shared Oxy ecosystem keystore instead of Expo's
 * generic `debug.keystore`.
 *
 * Willo has its own Android UID and gets the Oxy identity and device session
 * from Commons over signature-protected IPC: the `so.oxy.permission.IDENTITY`
 * and `so.oxy.permission.DEVICE_SESSION` permissions (declared by
 * `@oxy.so/app-preset`) are signature-level, so Android grants them only to an
 * app signed with the SAME certificate as Commons, and every Oxy app declares
 * them. A debug build signed with Expo's keystore cannot be installed next to
 * Oxy, Commons or Mention — Android rejects it with
 * `INSTALL_FAILED_DUPLICATE_PERMISSION` — and Commons would refuse it anyway.
 * The preset's own `withOxyAndroidRelease` already covers the release
 * buildType (`OXY_UPLOAD_*`); this is the same idea for the one a developer
 * installs on their phone.
 *
 * The credentials come from Gradle properties — `~/.gradle/gradle.properties`
 * or `-P` on the command line — so the keystore and its password never go near
 * the repository. Without them the build falls back to Expo's keystore, so a
 * contributor who doesn't have the Oxy keystore can still build and run.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so this has to
 * live in a plugin or it is lost the next time anyone regenerates it.
 */

const { withAppBuildGradle } = require('expo/config-plugins');

const STORE_FILE = 'OXY_DEBUG_STORE_FILE';

const GENERATED_DEBUG_SIGNING = `        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }`;

const OXY_DEBUG_SIGNING = `        debug {
            // The Oxy signature permissions (Commons' identity and the shared
            // device session) are granted only to apps with the same
            // signature, so a build meant for a phone that already has Oxy
            // apps signs with the ecosystem key. Falls back to Expo's own
            // debug keystore when the properties aren't set. See
            // plugins/withOxyDebugSigning.js.
            storeFile file(findProperty('${STORE_FILE}') ?: 'debug.keystore')
            storePassword findProperty('OXY_DEBUG_STORE_PASSWORD') ?: 'android'
            keyAlias findProperty('OXY_DEBUG_KEY_ALIAS') ?: 'androiddebugkey'
            keyPassword findProperty('OXY_DEBUG_KEY_PASSWORD') ?: 'android'
        }`;

module.exports = function withOxyDebugSigning(config) {
  return withAppBuildGradle(config, config => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(`[withOxyDebugSigning] Expected a Groovy app/build.gradle, got ${config.modResults.language}.`);
    }
    if (config.modResults.contents.includes(STORE_FILE)) return config;
    if (!config.modResults.contents.includes(GENERATED_DEBUG_SIGNING)) {
      throw new Error(
        '[withOxyDebugSigning] Could not find the generated signingConfigs.debug block in ' +
          'app/build.gradle. The Expo template changed — update this plugin instead of editing android/ by hand.',
      );
    }
    config.modResults.contents = config.modResults.contents.replace(GENERATED_DEBUG_SIGNING, OXY_DEBUG_SIGNING);
    return config;
  });
};
